#!/bin/bash

s1-docker() {
  # if `github help` is called then display information on how to use the script
  if [[ $1 =~ "help" ]]; then
    echo "Bash commands to interact with docker

Available commands are:
  s1-docker rmc          Remove all containers
  s1-docker stop         Stops docker"
    return;
  fi

  eval "$(docker-machine env default)"

  if [[ $1 =~ "rmc" ]]; then 
    eval "$(docker rm $(docker ps -a -q))"
    return;
  fi

  if [[ $1 =~ "stop" ]]; then 
    eval "$(docker stop $(docker ps -q))"
    return;
  fi
}
