#!/bin/bash

s1-docker() {
  # if `github help` is called then display information on how to use the script
  if [[ $1 =~ "help" ]]; then
    echo "Bash commands to interact with docker

Available commands are:
  s1-docker rmc          Remove all containers
  s1-docker stop         Stops all running docker containers
  s1-docker rmd          Remove all data volumes"
    return;
  fi

  if [[ $1 =~ "rmd" ]]; then 
    docker volume rm $(docker volume ls -q )
    return;
  fi

  if [[ $1 =~ "rmc" ]]; then 
    docker rm $(docker ps -a -q)
    return;
  fi

  if [[ $1 =~ "stop" ]]; then 
    echo "Stopping all containers..."
    docker stop $(docker ps -q)
    return;
  fi
}
